name = "www-d1-api"
account_id = "7712e75c497be262dad6a07f2378e10d"
compatibility_date = "2026-08-26"

[[d1_databases]]
binding = "DB"
database_name = "workwithvrajesh-db"
database_id = "3d54fc00-0b85-4b29-a63c-a3527785ba92"
